function ApplyBC(M4,Maps,fileID)
fprintf(fileID,'*Heading\n** Job name: InSitu191109Si_MyS_I_1 Model name: Model-1');
fprintf(fileID,'** Generated by: Abaqus/CAE 2016');
fprintf(fileID,'*Preprint, echo=NO, model=NO, history=NO, contact=NO\n**\n** PARTS\n**');
fprintf(fileID,'*Part, name=sample');
'** ASSEMBLY\n**\n*Assembly, name=Assembly\n**  \n*Instance, name=sample-1, part=sample';
modelinp = 'P:\Abdo\EBSD Data\19-12-13  InSitu DSS - Bone\Spot 5\800_10nA_20kV\4\4\abaqus_model.inp';
%%
[~,xc] = ismember(M4.Nodes(:,1),M4.Elements(:,2:end));
Nodes = M4.Nodes;
for ik =length(Nodes):-1:1
    if xc(ik)==0
        Nodes(ik,:)=[];
    end
end

%% find relative values
% interpolate DVC results on the FE mesh
alldata = [Maps.X1(:) Maps.Y1(:) Maps.Ux(:) Maps.Uy(:)];
Fx = scatteredInterpolant(alldata(:,1),alldata(:,2),alldata(:,3),'natural');
Fy = scatteredInterpolant(alldata(:,1),alldata(:,2),alldata(:,4),'natural');
Nodes(:,4) = Fx(Nodes(:,2),Nodes(:,3));  % Ux
Nodes(:,5) = Fy(Nodes(:,2),Nodes(:,3));  % Uy

%% write the .INPfile patches  define the node sets 
patchASSEM = cell(2*length(Nodes),1);
for k=1:size(Nodes,1)
    str1 = strcat('*Nset, nset=_XEBSDBC-',num2str(Nodes(k,1)),', internal, instance=sample-1');
    str2 = strcat(num2str(Nodes(k,1)),',');
    patchASSEM(k*2-1) =  cellstr(str1);
    patchASSEM(k*2)   =  cellstr(str2);
end
                  
%% define the boundary conditions (commented by Yixuan)
patchBC    = cell(3*length(Nodes)+1,1);
patchBC(1) =  cellstr('*BOUNDARY, OP=NEW');
for k = 1:size(Nodes,1)
    if ~isempty(Nodes(k,4)) && Nodes(k,4)==0
        str1 = strcat('_XEBSDBC-',num2str(Nodes(k,1)),', 1, 1, ',num2str(Nodes(k,4)));
        str2 = strcat('_XEBSDBC-',num2str(Nodes(k,1)),', 2, 2, ',num2str(Nodes(k,5)));
        patchBC(k*3-1) =  cellstr(str1);
        patchBC(k*3)   =  cellstr(str2);
    end
end

%% Parse blank INP file
fid = fopen(modelinp, 'r');
C   = textscan(fid, '%s', 'Delimiter', '\n');
fclose(fid);

%% Find where to inject the BC patch
injptBC = strfind(C{1}, '*Static');
rows    = find(~cellfun('isempty', injptBC));
injptBC = rows +1;

%% Find where to inject the ASSEM patch
injptASSEM = strfind(C{1}, '*End Assembly');
rows       = find(~cellfun('isempty', injptASSEM));
injptASSEM = rows -1;

%% Append data to the INP file
part1 = C{1}(1:injptASSEM);
part2 = C{1}(injptASSEM+1:injptBC);
part3 = C{1}(injptBC+1:end);
finalform = [part1;patchASSEM;part2;patchBC;part3];

%% Write outputfile
outputname = 'P:\Abdo\EBSD Data\19-12-13  InSitu DSS - Bone\Spot 5\800_10nA_20kV\4\4\abk.inp';
fileID = fopen(outputname,'w');
for i=1:size(finalform,1)
    if ~isempty(finalform{i})
    stri = finalform(i);
    fprintf(fileID,'%s\n',char(stri));
    end
end
fclose(fileID);