function Inp4Grains(M4Nodes,M4Elements,resultsDir)    
counters = 1;       count = 0;
for iv = 1:length(M4Elements)
    for i=1:length(M4Elements{iv}) 
        count = count+1;
        Elements{count}=M4Elements{iv}(i,2:end); 
    end
    Elements_Sets{iv}.Name = ['Set' num2str(iv)];  
    Elements_Sets{iv}.Elements_Type = 'CPS4';
    Elements_Sets{iv}.Elements = M4Elements{iv}(:,1);
    counters = counters+i;
end

%%
Filename=[resultsDir '\All_Grains_abaqus_model.inp'];
fileID = fopen(Filename, 'w');
fprintf(fileID,'*Heading\n'); 
fprintf(fileID,'** Job name: S13_1250_R_Twin_Mid_1 Model name: Model-1\n'); 
fprintf(fileID,'** Generated by: Abaqus/CAE 2016\n'); 
fprintf(fileID,'*Preprint, echo=NO, model=NO, history=NO, contact=NO\n'); 
fprintf(fileID,'**\n'); 
fprintf(fileID,'** PARTS\n'); 
fprintf(fileID,'**\n'); 
fprintf(fileID,'*Part, name=sample\n'); 
fprintf(fileID,'*Node\n');   %Generate Nodes in Input File

[NNode, ND] = size(M4Nodes);
if      ND == 3     % 2D                               
    for i=1:1:NNode   
        fprintf(fileID,['\t' num2str(M4Nodes(i,1)) ', ' num2str(M4Nodes(i,2)) ', '...
            num2str(M4Nodes(i,3)) '\n']); 
    end
elseif  ND==4       % 3D 
    for i=1:1:NNode
    fprintf(fileID,['\t' num2str(M4Nodes(i,1)) ', ' num2str(M4Nodes(i,2)) ', ' ...
        num2str(M4Nodes(i,3)) ', ' num2str(M4Nodes(i,4)) '\n']); 
    end      
end
fprintf(fileID,'\n');

%% Generate Elements in Input File
for i=1:length(Elements_Sets)
    if length(Elements_Sets) == 1
        fprintf(fileID,strcat('*ELEMENT, type=',Elements_Sets{i}.Elements_Type,'\n'));
    else
            fprintf(fileID,strcat('*ELEMENT, ELSET=',Elements_Sets{i}.Name,...
        ', TYPE=',Elements_Sets{i}.Elements_Type,'\n'));
    end
    for j=1:length(Elements_Sets{i}.Elements) %Loop for the elements in the elements set
        IE  = Elements_Sets{i}.Elements(j);        %Elements indices in elements sets
        NNN = [num2str(IE) ', '];
        for k=1:length(Elements{IE})    
            NNN = [NNN num2str(Elements{IE}(k)) ', '];
        end
    NNN = NNN(1:end-2);
    fprintf(fileID,[NNN '\n']);
    end
fprintf(fileID,'\n');
end
fprintf(fileID,'\n');
fclose(fileID);
end